# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfa2a60ca7603dc9911d447aa3cd7b2f347200519e3ed5438c702f7b8d85099d4c9138a86c480ce9f70817d9676a5faaf4e43b2bd8df84c3200c6fd994a48f37

test:
  secret_key_base: ac722442b52ea93c6eeb48cb93a8553f520dbdcbd1804bef87f311d31556c7f0bb7d890e1291bfc837a6e8bcc9f94958de48717a2d6e813053460c0ab506d2a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
